import type { Metadata } from 'next'
import './globals.css'
import BackgroundVideo from '@/components/video/BackgroundVideo'
import NavBar from '@/components/commons/NavBar'
import Contents from '@/components/commons/Contents'
import { AuthUserProvider } from '@/provider/CommonProvider'
import QueryProviders from '@/provider/QueryClientProvider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout(
	props: Readonly<{
		children: React.ReactNode
	}>,
) {
	return (
		<html lang="en">
			<body className="relative min-h-screen w-full bg-black overflow-hidden flex flex-col text-white font-sans">
				<QueryProviders>
					{/* 백그라운드 비디오 재생 */}
					<BackgroundVideo />

					<AuthUserProvider>
						{/* 상단 헤더 (전역) */}
						<NavBar />
					</AuthUserProvider>
					{/* 실제 페이지 내용이 렌더링되는 곳 */}
					<Contents {...props} />
				</QueryProviders>
			</body>
		</html>
	)
}
